server:
  port: 1224

spring:
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
    show-sql: false

sekhmet:
  data-dir: ../data
  llm:
    provider: ${LLM_PROVIDER:openai}
    api-key: ${LLM_API_KEY:}
    base-url: ${LLM_BASE_URL:}
    model-name: ${LLM_MODEL_NAME:}
